on: 
  push:
    branches: [main]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4
      
      - uses: levibostian/decaf@0.17.2
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: decaf shebang https://github.com/levibostian/decaf-script-github-releases.git/shebang.sh@1.3.0 get
          get_next_release_version: decaf shebang https://github.com/levibostian/decaf-script-conventional-commits.git/shebang.sh@0.3.0
          deploy: decaf shebang https://github.com/levibostian/decaf-script-github-releases.git/shebang.sh@1.3.0 set
